// Commvault Backup & Cyber Resilience — Battle Card 2026
// Practice: Commvault | Product: Commvault Cloud Unity

const COMMVAULT_BACKUP = {
  practice: 'Commvault',
  product: 'Commvault Cloud Unity',
  competitors: 'Rubrik, Cohesity, Veeam, Druva, HYCU, Dell PowerProtect, IBM Storage Protect, Zerto',

  overview: {
    logo: '🛡',
    name: 'Commvault Cloud Unity',
    category: 'Cyber Resilience / Enterprise Backup / Data Protection',
    deployment: 'SaaS + On-Premises + Hybrid',
    targetUsers: 'CIO, CISO, IT Infrastructure, Backup Admins, Security Teams, BFSI, Government, Large Enterprise',
    productLaunch: '1996',
    marketPosition: 'Gartner Magic Quadrant Leader — 15th consecutive year (2026)',
    gartnerMQ: 'Enterprise Backup & Recovery 2026 (Leader — 15 consecutive)',
    description: 'Commvault is not simply a backup product. It is an enterprise cyber-resilience platform designed to protect, detect, govern and recover data, applications, identities and workloads across on-premises, hybrid cloud, SaaS and multicloud environments. Commvault Cloud Unity brings data security, identity resilience and cyber recovery into a cloud-native platform. The core positioning: Protect → Detect → Isolate → Validate → Recover → Rebuild — not merely Backup → Restore.',
  },

  keyFeatures: [
    { icon: '🌐', name: 'Heterogeneous Workload Coverage', description: 'Protects VMware, Hyper-V, Nutanix, physical servers, databases, NAS, object storage, Kubernetes, AWS, Azure, Google Cloud, Microsoft 365, SaaS, identity, long-term retention, tape and mainframe — one platform, one architecture.' },
    { icon: '🛡', name: 'Cyber Resilience Beyond Backup', description: 'Full Protect → Detect → Isolate → Validate → Recover → Rebuild lifecycle. Threat scanning, clean-point identification and synthetic recovery designed to construct recovery points from known-clean data.' },
    { icon: '🔑', name: 'Identity Resilience', description: 'Ransomware attacks Active Directory, Entra ID, privileged accounts, identity infrastructure and credentials — not just files. Commvault Cloud Unity explicitly combines data security, identity resilience and cyber recovery.' },
    { icon: '🏗', name: 'Deployment Flexibility', description: 'SaaS, on-premises or hybrid deployment — without forcing customers into a single infrastructure architecture. Works with existing storage: object, cloud, disk, tape, deduplication appliances and customer-owned infrastructure.' },
    { icon: '📦', name: 'Storage Flexibility & OEM Neutrality', description: 'Uses customer-owned storage, object storage, cloud, disk, tape and deduplication appliances. Strong counter to appliance-centric propositions. Protects Dell, HPE, Lenovo and any other infrastructure consistently.' },
    { icon: '🏦', name: 'Enterprise Retention & Compliance', description: 'Mature policy, retention and workload capabilities for banking, government, insurance, telecom, manufacturing and healthcare. Long-term retention as critical as ransomware protection in regulated industries.' },
    { icon: '🔄', name: 'Application-Centric Recovery', description: 'Recovers entire applications — VM + DB + AD + middleware + configuration + dependencies — not just isolated VMs or data copies. Customers want to restore their banking application, not just a VM.' },
    { icon: '🤖', name: 'AI / Conversational Operations', description: 'Conversational AI interface for natural-language interaction with Commvault Cloud — resilience tasks, health checks and recovery workflows without console-driven operations. Moving backup administration to AI-assisted resilience operations.' },
  ],

  strengths: [
    'Broadest heterogeneous workload coverage in the market — VMware, physical, database, NAS, Kubernetes, SaaS, mainframe, tape, cloud',
    'Cyber resilience platform — threat detection, clean-point identification, identity recovery, not just backup',
    'OEM-neutral architecture — protects any vendor infrastructure including Dell, HPE, Cisco, Lenovo',
    'Deployment flexibility — SaaS, on-premises or hybrid without forcing infrastructure architecture change',
    'Storage flexibility — customer-owned storage, object, tape, cloud, appliances',
    'Identity resilience built-in — Active Directory, Entra ID, privileged account protection',
    'Gartner Leader 15 consecutive Magic Quadrants — proven enterprise track record',
    'Application-centric recovery — VM + DB + AD + dependencies, not isolated data copies',
    'Strong BFSI and regulated industry credentials — banking, government, insurance, telecom',
    'AI-assisted resilience operations — conversational interface, operational intelligence',
  ],

  weaknesses: [
    'Higher administrative complexity compared to Rubrik, Cohesity and HYCU',
    'Licensing model can be complex — requires careful scoping by workload and metric',
    'Perception as "legacy backup" among some greenfield SaaS-first buyers',
    'Druva and HYCU offer simpler SaaS-only models for pure-cloud environments',
    'Veeam has stronger channel relationships and installed base in SMB/mid-market',
    'Rubrik and Cohesity have stronger simplicity narrative in competitive bake-offs',
  ],

  discoveryQuestions: [
    'What are all the workloads you need to protect — VMware, physical, databases, NAS, Kubernetes, cloud, SaaS, mainframe, tape?',
    'How many backup products are you currently running across the estate?',
    'What is your current five-year backup TCO including servers, storage, licenses, DR copies, cloud and support?',
    'Where are your immutable copies and who can access or delete them?',
    'If your backup administrator\'s credentials are compromised at the same time as production — what trusted recovery copy remains?',
    'How do you identify the last-known-good recovery point after a ransomware incident?',
    'How frequently do you test recovery — and do you test application recovery or just backup job success?',
    'Can you recover the entire application — VM, database, Active Directory, middleware and dependencies — not just a single VM?',
    'What happens if Active Directory or Entra ID is compromised during a ransomware attack?',
    'How much backup data is going to public cloud and what are your cloud egress and storage costs?',
    'What happens when your data grows 30–40% annually — how does your backup architecture scale?',
    'What is your target MTCR — Mean Time to Cyber Recovery — and have you measured it?',
    'How many different workload types and retention policies do you need to protect?',
    'What percentage of your environment is Dell, HPE or another single OEM?',
    'Do you need pure SaaS simplicity or do you need SaaS plus enterprise workload, retention and storage flexibility?',
  ],

  recommendedResponses: [
    'Lead with the cyber-resilience platform positioning — Protect → Detect → Isolate → Validate → Recover → Rebuild. Not backup → restore.',
    'Against Rubrik simplicity objection: distinguish simplicity of deployment from capability across a heterogeneous estate. Test both against the complete workload matrix.',
    'Against Veeam installed-base objection: don\'t displace what works. Identify the gaps — identity resilience, clean-room recovery, cyber threat scanning, SaaS and application dependencies.',
    'Against Cohesity speed objection: backup throughput is one metric. Test restore speed, application recovery, ransomware recovery, recovery-point validation and operational effort.',
    'Against Druva SaaS objection: Commvault also offers cloud-native SaaS, plus deployment and storage flexibility for workloads requiring greater control.',
    'Against Dell integration objection: Do you want backup optimized around Dell infrastructure, or an OEM-neutral layer protecting Dell + HPE + cloud + SaaS consistently?',
    'Against IBM scale objection: compare operational simplicity and recovery speed — the question is whether your team can recover the business quickly during a cyber incident.',
    'Against Zerto RPO objection: position Commvault for backup + cyber resilience; Zerto for continuous replication DR. In some environments they are complementary, not mutually exclusive.',
    'Use the TCO attack: ask for current backup cost including servers, storage, licenses, DR copies, cloud, support and people — then add the cost of a failed ransomware recovery.',
    'Always use the A→R→Q→P formula: Acknowledge the competitor\'s strength → Reframe to the broader resilience requirement → Question the gap → Position Commvault value.',
  ],

  caseStudies: [
    {
      icon: '🎬',
      customer: 'Sony',
      type: 'Global Enterprise Consolidation',
      challenge: 'Fragmented protection across 5,000+ endpoints, global data centers, AWS and Azure — multiple backup silos, high TCO, operational complexity.',
      result: 'Consolidated to Commvault — 80% reduction in TCO, unified protection across endpoints, data centers and cloud. Single platform replacing multiple backup products.',
    },
    {
      icon: '🏦',
      customer: 'VKB-Bank',
      type: 'BFSI Backup Performance',
      challenge: 'Financial services organization requiring faster backup performance with HPE ProLiant infrastructure and regulatory data protection requirements.',
      result: 'Implemented Commvault with HPE ProLiant — approximately 50% improvement in backup performance. Strong BFSI reference for Indian banking conversations.',
    },
    {
      icon: '💼',
      customer: 'Financial Services Enterprise',
      type: 'Hybrid Data Modernization',
      challenge: 'Multiple clouds, legacy applications, complex retention requirements and front-end-TB economics driving need for modern hybrid data protection.',
      result: 'Selected Commvault for hybrid data modernization — multiple clouds, legacy application support, favorable TCO and enterprise cyber-recovery capabilities.',
    },
  ],

  keyCustomers: [
    { logo: '🎬', name: 'Sony',             industry: 'Technology / Media',     color: '#1a1a1a' },
    { logo: '🏦', name: 'VKB-Bank',         industry: 'Banking / BFSI',         color: '#003087' },
    { logo: '🏛', name: 'Government Sector', industry: 'Public Sector',          color: '#1a6b3a' },
    { logo: '📡', name: 'Telecom Enterprise', industry: 'Telecommunications',    color: '#e60000' },
    { logo: '🏭', name: 'Manufacturing',     industry: 'Industrial / Enterprise', color: '#ff6b00' },
    { logo: '🏥', name: 'Healthcare System', industry: 'Healthcare',             color: '#00897b' },
  ],

  competitorSummary: [
    {
      name: 'Rubrik',
      color: '#0078D4',
      marketPosition: 'Gartner Leader 2026',
      overview: 'Extremely simple UX, SaaS management, immutable architecture, cyber recovery, threat hunting, identity resilience, strong ransomware messaging and fast deployment. 2026 positioning includes Preemptive Recovery Engine and SaaS-based unified management.',
      strengths: ['Simple UX and fast deployment', 'SaaS management', 'Immutable architecture', 'Cyber recovery and threat hunting', 'Identity resilience', 'Predictable consumption model', 'Furthest in Completeness of Vision (Gartner 2026)'],
      weaknesses: ['Less breadth across heterogeneous workloads', 'Limited mainframe and tape support', 'Less deployment and storage flexibility', 'Higher cost in complex enterprise estates'],
      ourEdge: ['Broader workload depth — VMware, physical, database, NAS, mainframe, tape, Kubernetes, cloud', 'More deployment flexibility — SaaS, on-prem or hybrid', 'Greater storage flexibility — customer-owned, tape, object, cloud', 'Stronger enterprise retention and compliance capabilities'],
    },
    {
      name: 'Veeam',
      color: '#00B336',
      marketPosition: 'Gartner Leader 2026 — 10th consecutive, highest Ability to Execute',
      overview: 'Excellent VMware/virtualization heritage, very strong ecosystem, easy deployment, broad workload support, excellent channel presence, strong community and competitive pricing. 550,000+ customers globally.',
      strengths: ['Excellent VMware and virtualization protection', 'Very strong ecosystem and channel', 'Competitive pricing', 'Easy deployment and restore experience', 'Large installed base — strong incumbency', '550,000+ customers worldwide'],
      weaknesses: ['Cyber resilience depth below Commvault and Rubrik', 'Identity recovery capabilities less mature', 'Application-level recovery less comprehensive', 'Clean-room recovery workflows less developed'],
      ourEdge: ['Broader enterprise cyber resilience — threat detection, identity recovery, clean recovery', 'Application-centric recovery — VM + DB + AD + dependencies', 'Identity resilience built-in — AD and Entra ID protection', 'Key discovery question: What happens if backup admin credentials are compromised at the same time as production?'],
    },
    {
      name: 'Cohesity',
      color: '#FF6D00',
      marketPosition: 'Gartner Leader 2026',
      overview: 'Simple management, scale-out architecture, data security and management, strong ransomware protection, good hybrid-cloud proposition, strong Nutanix/VMware ecosystem and consolidation story.',
      strengths: ['Simple management and scale-out architecture', 'Data security and consolidation platform', 'Strong ransomware protection', 'Good hybrid-cloud proposition', 'Strong Nutanix/VMware ecosystem', 'Appliance simplicity story'],
      weaknesses: ['Less depth across heterogeneous workloads than Commvault', 'Appliance-centric model limits storage flexibility', 'Less mature enterprise tape and mainframe support'],
      ourEdge: ['Heterogeneous workload depth — physical, database, mainframe, tape, legacy workloads', 'Mature enterprise capabilities across regulated industries', 'OEM-neutral architecture — not tied to appliance ecosystem', 'Application recovery depth — not just backup throughput'],
    },
    {
      name: 'Druva',
      color: '#7B2D8B',
      marketPosition: 'Gartner Leader 2026',
      overview: 'Fully managed SaaS — no backup server, backup infrastructure or backup storage hardware. No upgrade cycles. 2026 Gartner positioning specifically emphasizes fully managed SaaS architecture.',
      strengths: ['Fully managed SaaS — zero infrastructure', 'No upgrade cycles or hardware management', 'Endpoint, M365 and SaaS-native protection', 'Simple deployment and operations'],
      weaknesses: ['Less deployment and storage flexibility', 'Less enterprise workload depth — physical, mainframe, tape', 'Less control over where long-term backup data resides', 'Can be more expensive at enterprise scale'],
      ourEdge: ['SaaS deployment plus on-premises and hybrid options', 'Deeper enterprise workload coverage — physical, database, mainframe, tape', 'More control over data residency and storage architecture', 'Better fit for regulated industries requiring data sovereignty'],
    },
    {
      name: 'Dell PowerProtect',
      color: '#007DB8',
      marketPosition: 'Gartner Leader 2026',
      overview: 'PowerProtect One — unified cyber-resilience platform combining Data Manager and Data Domain. Up to 75:1 deduplication. Strong installed base in Indian enterprises. Integrated appliance, storage integration and one-vendor support.',
      strengths: ['Strong Dell storage and server integration', 'PowerProtect Cyber Recovery vault', 'Up to 75:1 deduplication on appliances', 'One-vendor support model', 'Strong Indian enterprise installed base'],
      weaknesses: ['OEM-centric — best when environment is predominantly Dell', 'Less flexibility with non-Dell storage', 'If storage strategy changes, backup strategy must also change'],
      ourEdge: ['OEM-neutral architecture — protects Dell, HPE, Cisco, Lenovo and cloud consistently', 'Key question: What percentage of your environment is actually Dell? If 40–60%, Commvault advantage strengthens', 'Protects existing Dell storage investments while adding protection breadth'],
    },
  ],

  featureMatrix: {
    labels: { product: 'Commvault', comp1: 'Rubrik', comp2: 'Veeam', comp3: 'Cohesity' },
    rows: [
      { feature: 'Backup & Recovery',      product: 'green',  comp1: 'green',  comp2: 'green',  comp3: 'green'  },
      { feature: 'Cyber Resilience',        product: 'green',  comp1: 'green',  comp2: 'yellow', comp3: 'yellow' },
      { feature: 'Ransomware Detection',    product: 'green',  comp1: 'green',  comp2: 'yellow', comp3: 'green'  },
      { feature: 'Clean Recovery',          product: 'green',  comp1: 'green',  comp2: 'yellow', comp3: 'yellow' },
      { feature: 'Identity Resilience',     product: 'green',  comp1: 'green',  comp2: 'yellow', comp3: 'yellow' },
      { feature: 'Physical Servers',        product: 'green',  comp1: 'yellow', comp2: 'green',  comp3: 'yellow' },
      { feature: 'VM Protection',           product: 'green',  comp1: 'green',  comp2: 'green',  comp3: 'green'  },
      { feature: 'Database Protection',     product: 'green',  comp1: 'yellow', comp2: 'green',  comp3: 'green'  },
      { feature: 'NAS Protection',          product: 'green',  comp1: 'green',  comp2: 'green',  comp3: 'green'  },
      { feature: 'SaaS Protection',         product: 'green',  comp1: 'green',  comp2: 'green',  comp3: 'green'  },
      { feature: 'Kubernetes',              product: 'green',  comp1: 'green',  comp2: 'green',  comp3: 'green'  },
      { feature: 'Mainframe',               product: 'green',  comp1: 'red',    comp2: 'red',    comp3: 'red'    },
      { feature: 'Tape Support',            product: 'green',  comp1: 'red',    comp2: 'yellow', comp3: 'red'    },
      { feature: 'Long-term Retention',     product: 'green',  comp1: 'yellow', comp2: 'green',  comp3: 'yellow' },
      { feature: 'Multi-cloud',             product: 'green',  comp1: 'green',  comp2: 'green',  comp3: 'green'  },
      { feature: 'OEM Neutrality',          product: 'green',  comp1: 'yellow', comp2: 'green',  comp3: 'yellow' },
      { feature: 'Application Recovery',   product: 'green',  comp1: 'green',  comp2: 'green',  comp3: 'green'  },
      { feature: 'AI-Assisted Ops',         product: 'green',  comp1: 'green',  comp2: 'yellow', comp3: 'yellow' },
      { feature: 'Deployment Flexibility',  product: 'green',  comp1: 'yellow', comp2: 'green',  comp3: 'yellow' },
    ],
  },

  tcoData: {
    labels: { product: 'Commvault', comp1: 'Rubrik', comp2: 'Veeam', comp3: 'Cohesity' },
    maxValue: 100,
    totals: { product: '5-Year TCO: Contact Lauren', comp1: 'Evaluate per workload', comp2: 'Evaluate per workload', comp3: 'Evaluate per workload' },
    rows: [
      { component: 'Backup Software',       product: '₹₹₹',   comp1: '₹₹₹₹',  comp2: '₹₹',    comp3: '₹₹₹'  },
      { component: 'Backup Storage',        product: 'Flex',   comp1: 'SaaS',   comp2: 'Flex',   comp3: 'Appl' },
      { component: 'DR Copy',               product: '₹₹₹',   comp1: '₹₹₹',   comp2: '₹₹₹',   comp3: '₹₹₹'  },
      { component: 'Cloud Storage',         product: '₹₹',    comp1: '₹₹₹',   comp2: '₹₹',    comp3: '₹₹'   },
      { component: 'Cyber Vault',           product: 'Incl',   comp1: 'Incl',   comp2: 'Add-on', comp3: 'Incl' },
      { component: 'Support',               product: '₹₹₹',   comp1: '₹₹₹₹',  comp2: '₹₹',    comp3: '₹₹₹'  },
      { component: 'Admin Manpower',        product: '₹₹₹',   comp1: '₹₹',    comp2: '₹₹',    comp3: '₹₹'   },
      { component: 'Upgrade / Refresh',     product: 'SaaS',   comp1: 'SaaS',   comp2: '₹₹',    comp3: '₹₹₹'  },
      { component: 'Recovery Testing',      product: 'Auto',   comp1: 'Auto',   comp2: 'Manual', comp3: 'Auto' },
    ],
  },

  objectionHandling: [
    { objection: '"Rubrik is much simpler."', response: 'Agreed — Rubrik has a strong simplicity proposition. Let\'s measure that against the operational complexity of your actual environment. If you have 8–10 workload types, multiple retention policies and regulatory requirements, simplicity must include recovery — not just deployment. Test both platforms against the complete workload matrix.' },
    { objection: '"Veeam is cheaper."', response: 'It can be cheaper depending on workload and licensing model. Let\'s normalize the same protected workloads, retention, cloud capacity, immutability, support and recovery requirements and compare five-year TCO — not just acquisition price.' },
    { objection: '"Druva is fully SaaS and we don\'t want to manage backup infrastructure."', response: 'That\'s a strong advantage if the objective is eliminating backup infrastructure. Commvault also offers a cloud-native SaaS model while giving customers deployment and storage flexibility for workloads requiring greater control — or where data sovereignty is important.' },
    { objection: '"Cohesity is faster."', response: 'Backup throughput is one metric. Let\'s test restore throughput, application recovery, ransomware recovery, recovery-point validation and operational effort — because what the business experiences during an incident is recovery speed, not backup speed.' },
    { objection: '"Dell integrates with our existing storage."', response: 'That\'s an advantage. But if tomorrow your storage strategy changes from Dell to another platform, do you want the backup platform to change with it? Commvault can protect your existing Dell storage while also protecting HPE, Lenovo, cloud and SaaS consistently.' },
    { objection: '"IBM handles huge data volumes."', response: 'Yes — IBM is strong in large-scale enterprise environments, especially tape and mainframe. Let\'s compare not just how much data we can store, but how quickly and confidently the business can be recovered after a cyber incident.' },
    { objection: '"Zerto gives us seconds-level RPO."', response: 'Correct — and if continuous replication with very low RPO is the requirement, Zerto is a strong technology. The question is whether you also need enterprise backup, long-term retention, SaaS protection, ransomware detection, compliance and clean recovery. Commvault + Zerto can also be complementary in some architectures.' },
    { objection: '"We already have Veeam and it works perfectly."', response: 'That\'s a fair position — we don\'t replace something working simply for the sake of replacement. The question is whether your requirements have moved beyond backup into cyber resilience, identity recovery, clean-room recovery, SaaS and application-level recovery. Let\'s identify the gaps first.' },
    { objection: '"HYCU is much simpler for our Nutanix environment."', response: 'If the environment is primarily Nutanix, that\'s a valid advantage. But let\'s look beyond today\'s Nutanix footprint — databases, physical workloads, multiple clouds, SaaS, long-term retention, identity recovery and cyber-recovery requirements. Don\'t optimize backup for today\'s hypervisor. Optimize resilience for your five-year infrastructure.' },
  ],

  winLoss: {
    total: 50,
    won: 31,
    lost: 19,
    winRate: 62,
    competitors: [
      { label: 'vs Veeam',        wins: 14, pct: 58, color: '#00B336' },
      { label: 'vs Rubrik',       wins: 8,  pct: 53, color: '#0078D4' },
      { label: 'vs Cohesity',     wins: 9,  pct: 64, color: '#FF6D00' },
      { label: 'vs Dell PP',      wins: 12, pct: 70, color: '#007DB8' },
      { label: 'vs Druva',        wins: 7,  pct: 50, color: '#7B2D8B' },
    ],
    topMessages: [
      'Heterogeneous workload breadth — one platform for the entire estate',
      'Identity resilience — Active Directory and Entra ID protection',
      'OEM-neutral architecture — protects any vendor infrastructure',
      'Application-centric recovery — VM + DB + AD + middleware + dependencies',
      'Five-year TCO including recovery testing, ransomware cost and operations manpower',
    ],
  },

  aiCoach: {
    customerSays: 'We are evaluating Commvault against Rubrik and Veeam for enterprise cyber resilience and backup consolidation.',
    suggestedResponse: 'Apply the A→R→Q→P formula: Acknowledge the competitor strength → Reframe to the broader resilience requirement → Question the gap → Position Commvault value. Lead with: "Don\'t buy backup. Buy recoverability." Then: "If your backup administrator\'s credentials are compromised at the same time as production — what trusted recovery copy remains and how do you identify the last-known-good point?" This moves the conversation from backup price to cyber resilience cost.',
    recommendedCaseStudy: 'Sony — 80% TCO reduction, consolidated 5,000+ endpoints across data centers, AWS and Azure. VKB-Bank — 50% backup performance improvement in BFSI environment.',
    winProbability: 'HIGH',
    kvps: [
      'Broadest heterogeneous workload coverage in the market',
      'Cyber resilience: Protect → Detect → Isolate → Validate → Recover → Rebuild',
      'Identity resilience — AD, Entra ID, privileged account protection',
      'OEM-neutral: protects Dell, HPE, Cisco, Lenovo and any cloud consistently',
      'Application-centric recovery — not just VM backup',
      'Gartner Leader 15 consecutive Magic Quadrants',
      'Don\'t buy backup. Buy recoverability.',
    ],
  },

  pricingTiers: [
    {
      tier: 'Commvault Cloud (SaaS)',
      monthlyPrice: 'Subscription / Capacity-based',
      annualPrice: 'Contact Lauren for India pricing',
      features: ['Fully managed SaaS', 'Unified cyber-resilience platform', 'Identity + data + workload protection', 'AI-assisted operations', 'Threat detection + clean recovery'],
    },
    {
      tier: 'Commvault On-Premises',
      monthlyPrice: 'Perpetual / Subscription',
      annualPrice: 'Contact Lauren for India pricing',
      features: ['Full enterprise workload coverage', 'Customer-owned storage flexibility', 'Tape, mainframe, physical server support', 'Long-term retention and compliance', 'Hybrid deployment option'],
    },
    {
      tier: 'Commvault Hybrid',
      monthlyPrice: 'Hybrid subscription',
      annualPrice: 'Contact Lauren for India pricing',
      features: ['SaaS management + on-prem execution', 'Flexible storage — cloud, on-prem, tape', 'Best for enterprises requiring data sovereignty', 'Full enterprise breadth + cloud agility'],
    },
  ],
};

module.exports = COMMVAULT_BACKUP;
